#!/bin/bash
clear

#Allows the server time to allow other applications enough time to open
sleep 2

#Running the webserver start script
cd ~/Rad_Server
screen -dmS webServer ./webServerStart

#Allow the webserver to start so that the http sever can connect
sleep 2

#Running the http start script
cd ~/Rad_Server
screen -dmS httpServer ./httpServerStart

#Running a new screen called command line
screen -mS commandLine

echo "RAD_Team Server"

$SHELL